apiVersion: v2
name: cluster-issuers
description: A Helm chart for cluster-issuers with cert-manager dependency
version: 0.1.0
keywords:
  - cert-manager
  - letsencrypt
dependencies:
  - name: cert-manager
    version: "1.17.x"
    repository: https://charts.jetstack.io
    condition: certManager.enabled
