# cert-manager subchart configuration
# See https://artifacthub.io/packages/helm/cert-manager/cert-manager
certManager:
  enabled: true
  crds:
    enabled: true
  # extraArgs:
  #   - --acme-http01-solver-nameservers=8.8.8.8:53

# ClusterIssuer definitions
clusterIssuers:
  letsencrypt-prod:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecret: letsencrypt-prod
    # email: override@example.com
    # solvers: []

  letsencrypt-staging:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecret: letsencrypt-staging

# Global settings
global:
  acme:
    email: your-email@example.com
    # solvers:
    #   - http01:
    #       ingress:
    #         class: nginx
