{{- $ingress := coalesce .Values.ingress dict }}
{{- $globalAnnotations := coalesce $ingress.annotations dict }}
{{- range .Values.endpoint.ports }}
  {{- if and .ingress .ingress.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $.Values.endpoint.name .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    {{- range $k, $v := merge $globalAnnotations (coalesce .ingress.annotations dict) }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ coalesce $ingress.className "nginx" }}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: {{ .ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.endpoint.name }}
                port:
                  number: {{ .port }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
