{{- $globalAnnotations := .Values.ingress.annotations | default dict }}
{{- range .Values.endpoint.ports }}
  {{- if and .ingress.enabled .ingress.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $.Values.endpoint.name .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    {{- range $k, $v := merge $globalAnnotations (.ingress.annotations | default dict) }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: {{ .ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.endpoint.name }}
                port:
                  number: {{ .port }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
