apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.endpoint.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.endpoint.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- end }}
