{{- range $name, $issuer := .Values.clusterIssuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
spec:
  acme:
    email: {{ default $.Values.global.acme.email $issuer.email }}
    server: {{ $issuer.server }}
    privateKeySecretRef:
      name: {{ $issuer.privateKeySecret }}
    solvers:
{{- if hasKey $issuer "solvers" }}
{{ toYaml $issuer.solvers | indent 4 }}
{{- else if hasKey $.Values.global.acme "solvers" }}
{{ toYaml $.Values.global.acme.solvers | indent 4 }}
{{- else }}
    - http01:
        ingress:
          class: nginx
{{- end }}
---
{{- end }}
