name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yaml'
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Create Helm index
        run: |
          mkdir -p ./gh-pages
          helm package charts/* --destination ./gh-pages
          helm repo index ./gh-pages --url https://es6kr.github.io/nginx-cert-issuers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
