name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yaml'
      - 'charts/**'

permissions: read-all

jobs:
  workflow:
    name: Helm Workflows
    uses: action-stars/helm-workflows/.github/workflows/release.yaml@0b498f1b9096b956f66f50954864e477dc3a639e # v0.8.5
    secrets:
      oci_password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    with:
      publish_oci: true
